# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_DialogNewEntry.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(546, 493)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_simid = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_simid.setObjectName("lineEdit_simid")
        self.horizontalLayout.addWidget(self.lineEdit_simid)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_mediawiki = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_mediawiki.setObjectName("lineEdit_mediawiki")
        self.horizontalLayout.addWidget(self.lineEdit_mediawiki)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_path = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.horizontalLayout_2.addWidget(self.lineEdit_path)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.textEdit_description = QtWidgets.QTextEdit(Dialog)
        self.textEdit_description.setObjectName("textEdit_description")
        self.verticalLayout.addWidget(self.textEdit_description)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.textEdit_tags = QtWidgets.QTextEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_tags.sizePolicy().hasHeightForWidth())
        self.textEdit_tags.setSizePolicy(sizePolicy)
        self.textEdit_tags.setObjectName("textEdit_tags")
        self.verticalLayout.addWidget(self.textEdit_tags)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.lineEdit_simtype = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_simtype.setObjectName("lineEdit_simtype")
        self.horizontalLayout_3.addWidget(self.lineEdit_simtype)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_simid, self.lineEdit_mediawiki)
        Dialog.setTabOrder(self.lineEdit_mediawiki, self.lineEdit_path)
        Dialog.setTabOrder(self.lineEdit_path, self.textEdit_description)
        Dialog.setTabOrder(self.textEdit_description, self.textEdit_tags)
        Dialog.setTabOrder(self.textEdit_tags, self.lineEdit_simtype)
        Dialog.setTabOrder(self.lineEdit_simtype, self.buttonBox)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Create new Database Entry"))
        self.label.setText(_translate("Dialog", "Simid:"))
        self.label_2.setText(_translate("Dialog", "MediaWiki"))
        self.label_3.setText(_translate("Dialog", "Path:"))
        self.label_4.setText(_translate("Dialog", "Description:"))
        self.label_5.setText(_translate("Dialog", "Tags & Keywords:"))
        self.label_6.setText(_translate("Dialog", "Simtype:"))

