# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1444, 896)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameSide = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameSide.sizePolicy().hasHeightForWidth())
        self.frameSide.setSizePolicy(sizePolicy)
        self.frameSide.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSide.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSide.setObjectName("frameSide")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frameSide)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget = QtWidgets.QWidget(self.frameSide)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MySearch_lineEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MySearch_lineEdit.sizePolicy().hasHeightForWidth())
        self.MySearch_lineEdit.setSizePolicy(sizePolicy)
        self.MySearch_lineEdit.setObjectName("MySearch_lineEdit")
        self.horizontalLayout.addWidget(self.MySearch_lineEdit)
        self.MySearch_pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MySearch_pushButton.sizePolicy().hasHeightForWidth())
        self.MySearch_pushButton.setSizePolicy(sizePolicy)
        self.MySearch_pushButton.setObjectName("MySearch_pushButton")
        self.horizontalLayout.addWidget(self.MySearch_pushButton)
        self.gridLayout_5.addWidget(self.widget, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(400, 10, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.frameSide)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 3, 0, 1, 1)
        self.layout_sideMenu = QtWidgets.QVBoxLayout()
        self.layout_sideMenu.setObjectName("layout_sideMenu")
        self.gridLayout_5.addLayout(self.layout_sideMenu, 4, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frameSide)
        self.frameMain = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameMain.sizePolicy().hasHeightForWidth())
        self.frameMain.setSizePolicy(sizePolicy)
        self.frameMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMain.setObjectName("frameMain")
        self.gridLayout = QtWidgets.QGridLayout(self.frameMain)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.frameMain)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.MyTabLabJournalIndex = QtWidgets.QWidget()
        self.MyTabLabJournalIndex.setObjectName("MyTabLabJournalIndex")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.MyTabLabJournalIndex)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget.addTab(self.MyTabLabJournalIndex, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.frameMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1444, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MySearch_lineEdit.setText(_translate("MainWindow", "Search (goto)"))
        self.MySearch_pushButton.setText(_translate("MainWindow", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MyTabLabJournalIndex), _translate("MainWindow", "Overview"))

